/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_practice_jni_JNIHelloWorld */

#ifndef _Included_com_practice_jni_JNIHelloWorld
#define _Included_com_practice_jni_JNIHelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_practice_jni_JNIHelloWorld
 * Method:    fping
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_practice_jni_JNIHelloWorld_fping
  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
