/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_practice_dubbo_springboot_Fpingimpl */

#ifndef _Included_org_practice_dubbo_springboot_Fpingimpl
#define _Included_org_practice_dubbo_springboot_Fpingimpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_practice_dubbo_springboot_Fpingimpl
 * Method:    fping
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_practice_dubbo_springboot_Fpingimpl_fping
  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
